spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MariaDBDialect
  datasource:
    url: jdbc:mariadb://localhost:3306/smartwaste
    username: root
    password: 1234